BEGIN;
SET default_tablespace = pg_default;
CREATE TABLE IF NOT EXISTS arena (
	id SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS squad (
	id SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	rank SMALLINT NOT NULL,
	arena_id SMALLINT REFERENCES arena(id)
);
CREATE TABLE IF NOT EXISTS stat (
	id SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	hit_points SMALLINT NULL,
	defense_points SMALLINT NULL,
	damage_points SMALLINT NULL,
	health_points SMALLINT NULL -- age SMALLINT NOT NULL
);
DO $$ BEGIN IF NOT EXISTS (
	SELECT 1
	FROM pg_type
	WHERE typname = 'transaction_type'
) THEN CREATE TYPE transaction_type AS ENUM ('income', 'expense');
END IF;
END $$;
CREATE TABLE IF NOT EXISTS storage (
	id SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	type transaction_type NOT NULL,
	wood SMALLINT NULL,
	food SMALLINT NULL,
	gold SMALLINT NULL,
	stone SMALLINT NULL
);
CREATE TABLE IF NOT EXISTS unit (
	id SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	squad_id SMALLINT REFERENCES squad(id),
	stat_id SMALLINT REFERENCES stat(id) ON DELETE CASCADE,
	storage_id SMALLINT REFERENCES storage(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS market (
	unit_id SMALLINT UNIQUE REFERENCES unit(id) ON DELETE CASCADE,
	tax SMALLINT NOT NULL
);
CREATE TABLE IF NOT EXISTS university (
	unit_id SMALLINT UNIQUE REFERENCES unit(id) ON DELETE CASCADE,
	research_time SMALLINT NOT NULL
);
CREATE TABLE IF NOT EXISTS equipment (
	id SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	unit_id SMALLINT REFERENCES unit(id) ON DELETE CASCADE,
	stat_id SMALLINT REFERENCES stat(id) ON DELETE CASCADE,
	storage_id SMALLINT REFERENCES storage(id) ON DELETE CASCADE
);
DO $$ BEGIN IF NOT EXISTS (
	SELECT 1
	FROM pg_type
	WHERE typname = 'skill_type'
) THEN CREATE TYPE skill_type AS ENUM (
	'attack',
	'defend',
	'heal',
	'kick',
	'bash',
	'dash',
	'rally'
);
END IF;
END $$;
CREATE TABLE IF NOT EXISTS skill (
	id SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	type skill_type NOT NULL,
	unit_id SMALLINT REFERENCES unit(id) ON DELETE CASCADE,
	stat_id SMALLINT REFERENCES stat(id) ON DELETE CASCADE,
	storage_id SMALLINT REFERENCES storage(id) ON DELETE CASCADE
);
COMMIT;